# Generated by Django 5.1.1 on 2024-09-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quick_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
